#!/usr/bin/env python3
"""Build MaterialOutlinedIconCategories.kt from Material Symbols metadata + our icon index.

Download metadata (large):
  curl -sS 'https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true' \
    -o build/material_symbols_icons.json

Then:
  python3 scripts/gen_material_icon_categories.py build/material_symbols_icons.json \\
    app/src/main/java/com/lu4p/fokuslauncher/ui/components/generated/MaterialOutlinedIconIndex.kt \\
    app/src/main/java/com/lu4p/fokuslauncher/ui/components/generated/MaterialOutlinedIconCategories.kt

Then refresh the APK icon subset:
  python3 scripts/gen_shipped_outlined_icons.py ...
"""
from __future__ import annotations

import json
import re
import sys

OUTLINED = "Material Symbols Outlined"


def compose_to_google(name: str) -> str:
    if name.startswith("_"):
        return name[1:].lower()
    s = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s)
    s = re.sub(r"([A-Za-z])([0-9])", r"\1_\2", s)
    s = re.sub(r"([0-9])([A-Za-z])", r"\1_\2", s)
    return s.lower()


def load_icon_names(index_path: str) -> list[str]:
    text = open(index_path, encoding="utf-8").read()
    return re.findall(r'^        "([^"]+)",?$', text, re.MULTILINE)


def load_google_categories(json_path: str) -> dict[str, str]:
    raw = open(json_path, encoding="utf-8").read()
    if raw.startswith(")]}'"):
        raw = raw[4:]
    data = json.loads(raw)
    by_name: dict[str, str] = {}
    for icon in data["icons"]:
        if OUTLINED in icon.get("unsupported_families", ()):
            continue
        cats = icon.get("categories") or ()
        if not cats:
            continue
        n, cat = icon["name"], cats[0]
        prev = by_name.get(n)
        if prev is None or len(cat) > len(prev):
            by_name[n] = cat
    return by_name


def kotlin_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(2)
    json_path, index_path, out_path = sys.argv[1:4]
    google = load_google_categories(json_path)
    names = load_icon_names(index_path)
    pairs: list[tuple[str, str]] = []
    for cn in names:
        gid = compose_to_google(cn)
        cat = google.get(gid)
        if cat:
            pairs.append((cn, cat))
    pairs.sort(key=lambda p: (p[1].lower(), p[0].lower()))
    lines = [
        "package com.lu4p.fokuslauncher.ui.components.generated",
        "",
        "// Generated by scripts/gen_material_icon_categories.py from Google Fonts Material Symbols metadata.",
        "// Keys match MaterialOutlinedIconIndex / Icons.Outlined.* file basenames. Values are API category labels (English).",
        "// Icons with no Symbols-outlined metadata entry are grouped under icon_cat_other in the app.",
        "internal object MaterialOutlinedIconCategories {",
        "",
        '    @JvmField',
        "    val GOOGLE_CATEGORY_BY_ICON_NAME: Map<String, String> = mapOf(",
    ]
    for cn, cat in pairs:
        lines.append(f'        "{kotlin_escape(cn)}" to "{kotlin_escape(cat)}",')
    lines.append("    )")
    lines.append("}")
    lines.append("")
    open(out_path, "w", encoding="utf-8").write("\n".join(lines))
    print(f"Wrote {len(pairs)} icon categories to {out_path} ({len(names) - len(pairs)} without metadata)")


if __name__ == "__main__":
    main()
