#!/usr/bin/env python3
"""Generate MaterialShippedOutlinedIcons.kt: static map of outlined icons we ship.

Includes every glyph that appears in icon pickers (same omission rules as MinimalIcons) plus
every Icons.Outlined.* used by legacyAliases so stored snake_case keys keep resolving. Replaces
reflection + blanket ProGuard keep so R8 can strip the rest of material-icons-extended.

Run from repo root after updating the full index / categories:
  python3 scripts/gen_shipped_outlined_icons.py \\
    app/src/main/java/com/lu4p/fokuslauncher/ui/components/generated/MaterialOutlinedIconIndex.kt \\
    app/src/main/java/com/lu4p/fokuslauncher/ui/components/generated/MaterialOutlinedIconCategories.kt \\
    app/src/main/java/com/lu4p/fokuslauncher/ui/components/generated/MaterialShippedOutlinedIcons.kt
"""
from __future__ import annotations

import re
import sys

PICKER_OMITTED = frozenset({"Text", "Android", "Actions", "Home"})

# Icons.Outlined.* basenames from legacyAliases in MinimalIcons.kt (send uses AutoMirrored — skip).
LEGACY_OUTLINED = frozenset(
    {
        "Circle",
        "Apps",
        "Menu",
        "Category",
        "Email",
        "Mail",
        "Call",
        "Phone",
        "Contacts",
        "Link",
        "Share",
        "MusicNote",
        "Videocam",
        "CameraAlt",
        "Photo",
        "Image",
        "PlayArrow",
        "Palette",
        "Book",
        "Newspaper",
        "Headset",
        "Home",
        "Map",
        "Place",
        "LocationOn",
        "Directions",
        "Flight",
        "Alarm",
        "Timer",
        "CalendarMonth",
        "Event",
        "Person",
        "Favorite",
        "FavoriteBorder",
        "Bookmark",
        "BookmarkBorder",
        "VolunteerActivism",
        "Work",
        "Folder",
        "Code",
        "Settings",
        "AccountBalance",
        "ShoppingCart",
        "ShoppingBag",
        "Restaurant",
        "Gamepad",
        "Star",
        "StarBorder",
        "Cloud",
        "Search",
        "Close",
        "Add",
        "Delete",
        "ArrowBack",
        "CheckCircle",
        "ArrowForward",
        "ChevronRight",
        "Logout",
        "Cancel",
        "Notifications",
        "Lock",
        "DarkMode",
        "Language",
        "Translate",
    }
)


def load_index(index_path: str) -> list[str]:
    text = open(index_path, encoding="utf-8").read()
    return re.findall(r'^        "([^"]+)",?$', text, re.MULTILINE)


def load_categories(categories_path: str) -> dict[str, str]:
    text = open(categories_path, encoding="utf-8").read()
    pairs = re.findall(r'^\s+"([^"]+)"\s+to\s+"([^"]+)",?\s*$', text, re.MULTILINE)
    return dict(pairs)


def is_omitted_from_picker(name: str, google: dict[str, str]) -> bool:
    cat = google.get(name)
    if cat is None:
        return True
    return cat in PICKER_OMITTED


def main() -> None:
    if len(sys.argv) != 4:
        print(__doc__)
        sys.exit(2)
    index_path, categories_path, out_path = sys.argv[1:4]
    names = load_index(index_path)
    google = load_categories(categories_path)
    pickable = {n for n in names if not is_omitted_from_picker(n, google)}
    shipped = sorted(pickable | LEGACY_OUTLINED)

    lines = [
        '@file:Suppress("DEPRECATION")',
        "",
        "package com.lu4p.fokuslauncher.ui.components.generated",
        "",
        "// Generated by scripts/gen_shipped_outlined_icons.py — do not edit by hand.",
        "// Outlined icons included in the APK: pickers (MinimalIcons omission rules) + legacy Icons.Outlined aliases.",
        "import androidx.compose.material.icons.Icons",
        "import androidx.compose.material.icons.outlined.*",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "import java.util.TreeMap",
        "",
        "internal object MaterialShippedOutlinedIcons {",
        "",
        "    /** Sorted outlined glyph names shipped in the app (subset of MaterialIcons extended). */",
        "    @JvmField",
        "    val SHIPPED_NAMES: List<String> = listOf(",
    ]
    for n in shipped:
        lines.append(f'        "{n}",')
    lines.append("    )")
    lines.append("")
    lines.append("    @JvmField")
    lines.append("    val byName: Map<String, ImageVector> = run {")
    lines.append("        val m = TreeMap<String, ImageVector>()")
    for n in shipped:
        lines.append(f'        m["{n}"] = Icons.Outlined.{n}')
    lines.append("        m")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    open(out_path, "w", encoding="utf-8").write("\n".join(lines))
    print(
        f"Wrote {len(shipped)} shipped icons to {out_path} "
        f"(pickable={len(pickable)}, legacy_extra={len(shipped) - len(pickable)})"
    )


if __name__ == "__main__":
    main()
